fail_fast: true
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v6.0.0
        hooks:
            -   id: check-merge-conflict
            -   id: detect-private-key
            -   id: check-symlinks
            -   id: check-toml
            -   id: check-xml
            -   id: check-yaml
            -   id: forbid-new-submodules
            -   id: mixed-line-ending
            -   id: trailing-whitespace
                language: python
    -   repo: https://github.com/pre-commit/pygrep-hooks
        rev: v1.10.0  # Use the ref you want to point at
        hooks:
            -   id: python-no-eval
            -   id: python-no-log-warn
            -   id: python-use-type-annotations
    -   repo: https://github.com/asottile/pyupgrade
        rev: v3.20.0
        hooks:
            -   id: pyupgrade
                args: [ --py310-plus ]
    -   repo: https://github.com/ambv/black
        rev: 25.1.0
        hooks:
            -   id: black
                language_version: python3.9
    -   repo: https://github.com/asottile/blacken-docs
        rev: 1.19.1
        hooks:
            -   id: blacken-docs
